# Generated by Django 2.1 on 2018-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=70)),
                ('size', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('in_catalog', models.BooleanField(default=False, verbose_name='Show in catalog?')),
            ],
        ),
    ]
